zherczeg/sljit

- sljit_src/sljitExecAllocator.c
in HardenedBSD[1] and probably other security enhanced platforms, the
PROT_FLAGS passed to mmap won't be respected in some cases, leading
to the allocation of pages that lack execution permission and therefore
will trigger the application to segfault later.
detect the problem earlier by doing an mprotect of the recently allocated
page with the same permissions and if denied, discard it instead and
report an allocation problem upstream.
[1] https://github.com/HardenedBSD/hardenedBSD/wiki#pageexec-and-mprotect-aka-noexec
> check compiler page was given the expected PROT_FLAGS

- sljit_src/sljitExecAllocator.c
avoid using obsoleted in POSIX, SUSv2 getpagesize() and make
sure to use the correct MAP_ANON macro name that is expected
and failed back to in the rest of the codebase
> macos: make test for hardened runtime slightly more pedantic

- regex_src/regexJIT.h
- sljit_src/sljitConfig.h
- sljit_src/sljitConfigInternal.h
- sljit_src/sljitLir.h
Simply add a bunch of extern "C" to the headers to support using the library in C++ code.
> Make headers C++ friendly.

- sljit_src/sljitConfig.h
- sljit_src/sljitConfigInternal.h
- sljit_src/sljitUtils.c
Add SLJIT_UTIL_SIMPLE_STACK_ALLOCATION flag to use SLJIT_MALLOC/SLJIT_FREE to allocate/free the stacj
> Add SLJIT_UTIL_SIMPLE_STACK_ALLOCATION flag to use normal allocator for

- sljit_src/sljitProtExecAllocator.c
fd is not needed after the file is mmaped so there is no point on
keeping track of it or delaying closing it.
this also reduces the window other process might try to get a hold
of the file and therefore be able to manipulate the shared map.`
> protexec: close fd early

- sljit_src/sljitProtExecAllocator.c
avoid calling getenv in scenarios where it is not safe (like when
running setuid/setgid)
this should only be effective in NetBSD < 8, as anything that has
MAP_REMAPDUP is using a different implementation of the alloc_chunk
function that doesn't have this deficiency.
> netbsd: secure_getenv compat

- sljit_src/sljitProtExecAllocator.c
the backing file contents should not be accessible outside the running
process so make sure there are no RW permissions in the file created
for any user as early as possible.
> protexec: restrict file system permissions in the map files

- sljit_src/sljitProtExecAllocator.c
refactor create_tempfile to address:
- restrict additional dependencies to NetBSD < 8 or Linux
- error checking for TMPDIR to avoid failing to create the map files when invalid
- cleaner logic for failback so there are not double copies
- make sure P_tmpdir is used even in non debug/verbose builds
- simpler trimming logic for trailing '/' that keeps a working path to avoid breaking the open call
> protexec: refactor create_tempfile()

- Makefile
- doc/tutorial/array_access.c
- doc/tutorial/brainfuck.c
- doc/tutorial/branch.c
- doc/tutorial/first_program.c
- doc/tutorial/func_call.c
- doc/tutorial/loop.c
- doc/tutorial/struct_access.c
- doc/tutorial/temp_var.c
- sljit_src/sljitLir.h
This updates the doc/tutorial C files to be compatible with latest APIs.
The Makefile rules are also updated to only depend on dependent files, not the output directory.
> Fix doc/tutorial examples and improve Makefile rules

- sljit_src/sljitUtils.c
an alternative fix for #55 that avoid typos and simplify logic
> utils: avoid madvise portability problems

- sljit_src/sljitWXExecAllocator.c
while at it make some minor matching changes to the POSIX code to easy
maintenance.
> wxexec: windows support

- sljit_src/sljitExecAllocator.c
- sljit_src/sljitProtExecAllocator.c
- sljit_src/sljitUtils.c
Visual Studio 2019 throws a C4206 (file is empty) warning (only with /W4) while processing sljitUtils.c, which is apparently a bug on their part, and that this refactoring doesn't workaround.
still while a little intrusive, the result is more readable and less code.
as a plus the executable allocator macro makes the use of this util consistent with the rest and could help someone stuck with a non optimizer linker
> util: cleanup

- sljit_src/sljitConfigInternal.h
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativeX86_common.c
mostly fixes some build issues when using C89/C90
> build: pedantic

- Makefile
- README
- regex_src/regexJIT.c
- regex_src/regexMain.c
- sljit_src/sljitConfig.h
- sljit_src/sljitConfigInternal.h
- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeSPARC_common.c
- sljit_src/sljitNativeTILEGX_64.c
- sljit_src/sljitNativeX86_common.c
- test_src/sljitConfigPost.h
- test_src/sljitConfigPre.h
- test_src/sljitMain.c
- test_src/sljitTest.c
Furthermore support pre and post configuration headers for the compiler.
> Support allocator data for executable allocators

- API_CHANGES
- Makefile
- doc/tutorial/array_access.c
- doc/tutorial/brainfuck.c
- doc/tutorial/branch.c
- doc/tutorial/first_program.c
- doc/tutorial/func_call.c
- doc/tutorial/loop.c
- doc/tutorial/struct_access.c
- doc/tutorial/temp_var.c
- sljit_src/sljitLir.h
- test_src/sljitTest.c
minor fixes on top of recent changes to improve the development experience
> minor fixes to improve the development experience

- sljit_src/sljitLir.c
> Fixed minor typo in comment

- sljit_src/sljitConfigInternal.h
Just like in the case of building for iOS, the __clear_cache()
implementation is missing (eventhough it might be for different
reasons)
Promote the documented system provided call and improve
the warning in the code to avoid future regressions like the
one introduced in 0863c5499c8ebd3c274b46442e1a0a9633ad42e2
> windows: fix building in arm64 with clang

- test_src/sljitTest.c
Label even numbered tests for clarity's sake.
Test label: 4-80
> Label even numbered tests

- sljit_src/sljitNativeX86_common.c
This is commit 1 of https://github.com/zherczeg/sljit/pull/138
> Fix x86 inline asm register clobbers

- sljit_src/sljitNativeX86_common.c
This is commit 2 of https://github.com/zherczeg/sljit/pull/138
> Add tcc to the list of compilers using AT&T syntax

- sljit_src/allocator_src/sljitExecAllocatorCore.c
- sljit_src/allocator_src/sljitExecAllocatorFreeBSD.c
- sljit_src/sljitLir.c
This is an updated alternative to #148 which also fixes issues introduced with #151
> freebsd: implement system specific execallocator

- sljit_src/sljitLir.h
- test_src/sljitTest.c
Updated the tests, added more feature testing.  @carenas please check
> Improve atomic operation constraints

- sljit_src/sljitNativeLOONGARCH_64.c
> Implement copysign on LoongArch

- sljit_src/sljitNativeARM_32.c
Avoids SIGILL when running in older CPUs than armv7 (ex: Raspberry PI < 2)
Tested with QEMU using a softfp userland, but would work as well with hardfp (FPU is optional but common with those CPUs, even if it is not NEON).
Thumb2 with `march=armv6t2` not addressed yet
> arm: provide emulation for SLJIT_CTZ in ARMv6

- sljit_src/sljitNativeMIPS_32.c
- sljit_src/sljitNativeMIPS_64.c
- sljit_src/sljitNativeMIPS_common.c
While at it split the implementation into bit specific functions and move some helpful macros used by the 64bit version up as well as other moslty mechanical refactoring.
> mips: fix SLJIT_COPYSIGN in 32bit

- sljit_src/sljitLir.c
- sljit_src/sljitNativeLOONGARCH_64.c
- test_src/sljitTest.c
A few small improvements to SLJIT_COPYSIGN and its test
> loongarch: implement sljit_emit_fop2r()

- sljit_src/sljitNativeMIPS_common.c
Improve StatusFR detection by using a system provided interface
> mips: allow detection of StatusFR with prctl()

- sljit_src/sljitNativeLOONGARCH_64.c
When building aPCRE2 library that included these changes and that supports at least 2 different character sizes the following is shown:
```
/usr/bin/ld: ./.libs/libpcre2-16.a(libpcre2_16_la-pcre2_jit_compile.o): in function `.LANCHOR9':
pcre2_jit_compile.c:(.bss+0x160): multiple definition of `cpu_feature_list'; ./.libs/libpcre2-8.a(libpcre2_8_la-pcre2_jit_compile.o):pcre2_jit_compile.c:(.bss+0x160): first defined here
```
> loongarch: fix FTBFS when building as part of PCRE2

- sljit_src/sljitConfigInternal.h
Tested on QEMU LoongArch virt machine, which solved https://github.com/loongson-community/discussions/issues/36
> Add LoongArch float to integer conversion special cases

- sljit_src/sljitNativeLOONGARCH_64.c
Support addmul on LoongArch64 platform, tested on 3A6000 AOSC system.
> Support addmul on LoongArch64

- sljit_src/sljitNativeLOONGARCH_64.c
Fix LoongArch code for float temporary tests and code style clean up.
> Fix LoongArch float temporary tests

- sljit_src/sljitNativeLOONGARCH_64.c
Fix LoongArch code for temporary tests, which basically same as the RISC-V changes.
Tested under QEMU Loongnix & 3A6000 AOSC system.
> Fix LoongArch binary temporary tests

- sljit_src/sljitNativeLOONGARCH_64.c
This add temporary register support to select for LoongArch, tested under Loongson 3A6000 platform.
> Add temporary register support to select for LoongArch

- sljit_src/sljitNativeX86_common.c
re: https://github.com/PCRE2Project/pcre2/pull/407
> MSAN fix for cpuid

- sljit_src/sljitNativeX86_common.c
Address failure to build with [`tcc`](https://en.wikipedia.org/wiki/Tiny_C_Compiler) (and which could be argued is their fault anyway), but also prepare the code to be able to build when Intel Syntax is being used (ex: `gcc -masm=intel`) as well as improve compiler portability (Oracle Developer Studio C++ still needs and additional patch to build)
> x86: improve execute_get_xcr0_low() portability

- sljit_src/sljitNativeLOONGARCH_64.c
Add 128-bit shuffle operation support to LoongArch and fix compilation failure due to API changes. Tested on Loongson 3C5000 & Gentoo Linux.
Plus, I've notice that the atomic part has been rewritten, dropped the `fine-grained` only tag. so if LoongArch needs to add the `lr/sc` atomic support? If so, I'll do it as soon as possible.
> Add shuffle support for LoongArch

- sljit_src/sljitNativeX86_common.c
Solves a failure to build when using Oracle Developer Studio C++ compiler
and simplifies the logic used in this function. finally making the codebase
safe to build with Intel syntax enforced.
> x86: improve execute_cpuid() portability

- sljit_src/sljitNativeRISCV_common.c
clz, clzw, ctz, ctzw, rev8, rol, rolw, ror, rori, roriw, rorw, sext.b, sext.h, sh1add, sh2add, sh3add, zext.h
> Bitmanipulation instructions on RISC-V

- sljit_src/sljitNativeLOONGARCH_64.c
This fix test failure on LoongArch platform that support AMCAS. Tested under QEMU & Loongson 3A6000.
BTW, I do think adding a CI that tells us whether a PR will break some architecture or not is a need, which reduces our working strength, and also let us fix that failure in time.
> Add SLJIT_ATOMIC_USE_LS/CAS support to LoongArch

- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeLOONGARCH_64.c
- sljit_src/sljitNativeS390X.c
- sljit_src/sljitNativeX86_64.c
- test_src/sljitTest.c
- test_src/sljitTestSimd.h
Proper argument checks are still missing.
> Improve vector reg support

- .github/workflows/actions.yml
> Improve CI

- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeLOONGARCH_64.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeRISCV_common.c
refs https://github.com/php/php-src/pull/18218
> Fix spelling in C code comments

- sljit_src/sljitLir.h
This got me scratch my head for a moment
> Correct doc string for sljit_emit_jump
