- sljit_src/sljitUtils.c
Some legacy UNIX systems (like Tru64, HP-UX and AIX) use MAP_ANONYMOUS
instead of MAP_ANON, so make sure they won't need to fallback to the
case where no anonymous mapping is available (like in IRIX)
it has been since standarized by the Austin Group[1], that either name
is valid and should be considered equivalent.
While at it, add the sys/types.h that is indicated as required by the
documentation for completeness (eventhough I hadn't seen it needed)
[1] http://austingroupbugs.net/view.php?id=850
> src: consider fallback for MAP_ANON

- regex_src/regexJIT.c
- sljit_src/sljitConfigInternal.h
- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeSPARC_common.c
- sljit_src/sljitNativeTILEGX_64.c
- sljit_src/sljitNativeX86_32.c
- sljit_src/sljitNativeX86_64.c
- sljit_src/sljitNativeX86_common.c
- test_src/sljitTest.c
Intel Control-flow Enforcement Technology (CET):
https://software.intel.com/en-us/articles/intel-sdm
contains indirect branch tracking (IBT). When IBT is enabled, the
indirect branch target must start with ENDBR instruction.  When IBT
is enabled at the compile time, this patch does:
1. Emit ENDBR32/ENDBR64 at function entry.  ENDBR32/ENDBR64 are NOPs on
non-CET machines.
2. Add SLJIT_ENDBR to sljit_emit_op0 to generate ENDBR32/ENDBR64 for x86
processors.
> x86: Add SLJIT_ENDBR to sljit_emit_op0 to generate ENDBR32/ENDBR64

- test_src/sljitTest.c
A few patches to get things compile with VS2019.
1. VS2019 is more stringent about error C4146.
2. A minor compiler warning when calling sljit_set_target() in sljitTest.c.
3. One of the macros would generate code like "if (true) {}", suppressing C4127 to silence that.
> Patches for VS2019

- sljit_src/sljitNativeX86_32.c
Fix X86_32 sljit_emit_return not to over allocate instruction buffer.
> X86_32: Don't over allocate instruction buffer

- sljit_src/sljitConfigInternal.h
- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeSPARC_common.c
- sljit_src/sljitNativeTILEGX_64.c
- sljit_src/sljitNativeX86_32.c
- sljit_src/sljitNativeX86_64.c
- sljit_src/sljitNativeX86_common.c
- test_src/sljitTest.c
Intel Control-flow Enforcement Technology (CET):
https://software.intel.com/en-us/articles/intel-sdm
contains shadow stack (SHSTK).  When SHSTK is enabled, return address on
normal stack must match the one on shadow stack.  When SHSTK is enabled
at the compile time, this patch updates sljit with:
1. Before JIT return, if shadow stack is enabled, adjust shadow stack
so that the top of show stack matches the top of normal stack.  NB: It
is safe since shadow stack is read-only, you can only skip stack frame,
not jump to anywhere else.
2. Fix X86_32 emit_x86_instruction to properly encode (%ebp) so that
we can use TMP_REG1 as scratch register to unwind show stack in
sljit_emit_return.  NB: ECX is unusable since it isn't a scratch
register in sljit as shown in sljit test:
$ ./bin/sljit_test …
> x86: Enable shadow stack support

- sljit_src/sljitNativeX86_32.c
- sljit_src/sljitNativeX86_64.c
- sljit_src/sljitNativeX86_common.c
We need to preserve ECX when skipping frames for normal return.  Use
[esp] to save and restore ECX.
> X86-32: Preserve ECX when skipping frames for return

- sljit_src/sljitNativeX86_common.c
- test_src/sljitTest.c
1. Fix VS2019 compile error C4146.
2. Mark some unused arguments to suppress compile warnings.
> VS2019 patches

- sljit_src/sljitConfigInternal.h
Make SLJIT_API_FUNC_ATTRIBUTE configurable. This could be used to let e.g. PCRE export the sljit functions from it's dll. This is useful for applications who want to use PCRE2 *and* sljit independently. For this to happen, another small change must be done to PCRE.
> Make SLJIT_API_FUNC_ATTRIBUTE configurable from the outside

- test_src/sljitMain.c
- test_src/sljitTest.c
Allow scripted checking of a test failure, by indicating an
error with a non zero return.
while at it, correct the returned percentage.
> test: propagate sljit_test failure to the system

- sljit_src/sljitProtExecAllocator.c
while at it, make sure that munmap first parameter is properly
casted to avoid compilation warnings on systems that don't use
void * (ex: Solaris)
> src: avoid map leak on failure

- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- test_src/sljitTest.c
the use of indexing modes when loading/storing has a[1]
limited range that was being validated incorrectly.
correct the logic and make sure tests are added to prevent
regressions which will otherwise show in at least linux
aarch64 with a modern clang as shown by:
In file included from sljit_src/sljitLir.c:2107:
sljit_src/sljitNativeARM_64.c:1881:43: warning: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
if ((mem & OFFS_REG_MASK) || (memw > 255 && memw < -256))
~~~~~~~~~~~^~~~~~~~~~~~~~
sljit_src/sljitNativeARM_64.c:1931:43: warning: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
if ((mem & OFFS_REG_MASK) || (memw > 255 && memw < -256))
~~~~~~~~~~~^~~~~~~~~~~~~~
similar code from all other ARM architectures was …
> arm: correctly validate memw in sljit_emit_[f]mem

- sljit_src/sljitProtExecAllocator.c
make sure we account for both the chunk_header and block_header when
freeing the chunk
> avoid leak when free_chunk in sljitProtExecAllocator

- sljit_src/sljitProtExecAllocator.c
the experimental sljitProtExecAllocator uses file backed maps to
workaround W^X policies and is therefore incompatible with fork()
NetBSD allows anonymous pages to have multiple pages with different
permissions by using mremap with the MAP_REMAPDUP flag so use that
instead.
> netbsd: implement non file backed alternative for sljitProtExecAllocator

- test_src/sljitTest.c
otherwise failing in SE systems (ex: OpenBSD and HardenedBSD)
as well as reported by asan as shown by:
==151==ERROR: AddressSanitizer: heap-use-after-free on address 0x6210000dd518 at pc 0x000000428e30 bp 0x7ffe3fb99060 sp 0x7ffe3fb99050
READ of size 8 at 0x6210000dd518 thread T0
#0 0x428e2f in sljit_get_label_addr sljit_src/sljitLir.h:1384
#1 0x428e2f in test57 test_src/sljitTest.c:5515
#2 0x428e2f in sljit_test test_src/sljitTest.c:6652
#3 0x7feb57130041 in __libc_start_main (/lib64/libc.so.6+0x27041)
#4 0x4013cd in _start (/usr/src/bin/sljit_test+0x4013cd)
label addresses must be copied out for using as they will be
wiped out once the compiler is destroyed.
> test: fix test57 not to use freed memory

- sljit_src/sljitProtExecAllocator.c
memfd_create is available in linux since kernel 3.17 with support
added in glibc (2.27), musl (1.1.20) and bionic (30).
it allows creating a tmpfs backed file without having to worry about
file system support, path location or permission or even file name
so is ideal for the kind of file that the ProtExecutionAllocator
needs to back its maps.
this solves the problemss reported in PCRE's bug 2455[1] where a JIT
enabled call that was compiled to use this experimental allocator
will fail because the selected TMPDIR was non executable (ironically
something commong in SE systems)
> protexec: allow using memfd_create for file backing creation

- sljit_src/sljitProtExecAllocator.c
in line with the current semantics make the map SHARED so it could
be used (with the same limitations and risks) like the old function
after fork()
Fixes: 9a3d3998dcaf151f5c562f8dde457790fe0d167c
> netbsd: cleanup alloc_chunk() in sljitProtExec for NetBSD >= 8

- sljit_src/sljitProtExecAllocator.c
support for O_TMPFILE was only added to linux, so while it will just error
out safely on other OS (notably NetBSD 7.2) and continue with the fallback
to use mkostemp, it is just not really needed.
> protexec: make open(O_TMPFILE) linux specific

- sljit_src/sljitUtils.c
- Haiku does not have madvise call.
- Illumos depends on the flags passed whether access to the old API or the newer one without madivse availability.
> Haiku/Illumos build fix :

- Makefile
after the bin directory was removed as a dependency to cleanup (and fix)
the dependency tracking, the following scenario is possibly breaking
builds:
$ git clean -fxd
Removing bin/
$ make
cc  -DSLJIT_CONFIG_AUTO=1 -Isljit_src -O2 -Wall -c -o bin/sljitMain.o test_src/sljitMain.c
error: unable to open output file 'bin/sljitMain.o': 'No such file or directory'
1 error generated.
make: *** [bin/sljitMain.o] Error 1
luckily I already fixed this problem in my "makefile" branch as
carenas/sljit@5618ec91b85df8427f38e36f850e1f828501aed4 so
implement it now by adding a sentinel to the bin directory and using
that instead as a dependency.
while at it, fix some other minor issues from that branch that are
hopefully something that we could agree on and might had even been
discussed recently.
CC: …
> build: reintroduce bin directory dependency

- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeMIPS_32.c
- sljit_src/sljitNativeMIPS_64.c
- sljit_src/sljitNativePPC_32.c
- sljit_src/sljitNativePPC_64.c
- sljit_src/sljitNativeSPARC_32.c
- sljit_src/sljitNativeX86_common.c
depending on the allocator used, the executable_offset parameter
might go unused.
there are already guards to avoid warnings in this case for x86
so do the same for all other architectures.
> build: avoid -Wunused-parameter like warnings

- sljit_src/sljitConfig.h
while not strictly needed, could be considered a missing part of #60 
includes some expanded blurbs so the differences between the provided "secure" allocators is clearer
> wxexec: update configuration

- sljit_src/sljitProtExecAllocator.c
NetBSD-7 is EOL as of June 29th 2020
originally suggested by @krytarowski in #46
> protexec: drop support for NetBSD < 8

- sljit_src/sljitExecAllocator.c
- sljit_src/sljitUtils.c
- sljit_src/sljitWXExecAllocator.c
while at it, cleanup the comments and avoid mixed declarations with code
or unnecessary use of non sljit types in the original code.
> util: consolidate all allocators to use get_page_alignment()

- sljit_src/sljitUtils.c
a careless refactoring broke the API by removing the global lock
functions completely if building without threads.
add the interfaces back for !!SLJIT_SINGLE_THREADED and avoid
doing more refactoring (for now)
Fixes: d1d893c97742cc3e84500a23f8d142c94680ba57
> util: avoid breaking API with sljit_{grab,release}_lock functions

- sljit_src/sljitLir.c
- sljit_src/sljitUtils.c
fixes the known race condition for the initialization of the executable allocator lock in windows (which also affects the unused global lock, which has been left intentionally untouched)
Fixes: PCRE BUG2377[1]
[1] https://bugs.exim.org/show_bug.cgi?id=2377
> util: fix race for initialization of executable allocator lock in windows

- sljit_src/sljitConfigInternal.h
this is the first commit (which is safe and ready to merge independently) of two, let me know otherwise on ways to improve it.
the second commit (c5d1355559d3482d130935c3374c3e5ba41bcc9c) does too much guessing of intention, and hence it is published mainly to gather feedback (even if it is simpler) as it will be better to understand why the exception was added when it doesn't seem to be needed.
the last version of macOS with x86-32 support will be EOL soon but wouldn't count on that considering they are still people using the last version of macOS with PowerPC that was EOL more than a decade ago.
> config: refactor fastcall setup

- Makefile
- sljit_src/sljitConfigInternal.h
- sljit_src/sljitNativeX86_common.c
- test_src/sljitTest.c
> test64: improve reliability by making allocation of executable memory independent of the allocator

- sljit_src/sljitNativeARM_T2_32.c
VS2019 patch for ARM_THUMB2
* Fix VS2019 compile error C4146 (unary minus operator applied to unsigned type).
> VS2019 patch for ARM_THUMB2

- Makefile
- sljit_src/sljitConfig.h
- sljit_src/sljitLir.h
- test_src/sljitConfigPre.h
Remove SLJIT_NO_DEFAULT_CONFIG and SLJIT_CUSTOM_CONFIG, and simplify
SLJIT_HAVE_SLJIT_CONFIG_PRE_H and SLJIT_HAVE_SLJIT_CONFIG_POST_H.
> Update configuration macros.

- sljit_src/sljitConfig.h
- sljit_src/sljitLir.h
- sljit_src/sljitUtils.c
- test_src/sljitTest.c
split into 2 phases to allow for a staged release for anyone that might care about ABI compatibility, but considering it is buggy and most likely not used it might as well be done in one fell swoop
> util: retire global lock

- sljit_src/sljitWXExecAllocator.c
Adds all missing parts to wxexec so it will be supported in NetBSD userspace (with or without MPROTECT) and could be used as a foundation for the macOS Big Sur work
Fixes: #56
> wxexec: better support for SE systems including NetBSD

- sljit_src/sljitExecAllocator.c
- sljit_src/sljitUtils.c
- test_src/sljitTest.c
open_dev_zero is inconsistently defined and used, so make sure that
all invocations use dev_zero internally in a thread safe way, and
while at it, make sure it doesn't leak the file handle on fork() if
support for O_CLOEXEC is available.
> util: add O_CLOEXEC to open_dev_zero and fix building without MAP_ANON in macOS

- Makefile
- sljit_src/sljitConfig.h
- sljit_src/sljitConfigInternal.h
- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeS390X.c
- test_src/sljitTest.c
implements (eventhough not in the cleanest or more performant way) all functionality that is required to pass all tests in both sljit and pcre2, but still lacking : 
- support for FPU and related functions (including vector operations)
- several unimplemented or partially implemented opcodes/features (obviously none needed by PCRE with the target CPU)
- no optimizations or profiling (including plenty of TODO that might need tackling before this can be released to users)
to enable will need to explicitly define SLJIT_CONFIG_S390X at compile time and it is known to work with z12 or later (using a Linux ONE remote machine[0], either directly or through CI) with a expected target of z13 or z14 for the needed vector support that is required for a high performance JIT in PCRE2.
Partially …
> s390x: initial port

- doc/tutorial/array_access.c
- doc/tutorial/brainfuck.c
- doc/tutorial/branch.c
- doc/tutorial/first_program.c
- doc/tutorial/func_call.c
- doc/tutorial/loop.c
- doc/tutorial/struct_access.c
- doc/tutorial/temp_var.c
The tutorial in `doc` folder is too old.
I just fixed them for **MSVC** 👍
```diff
-typedef SLJIT_FUNC (*func_t)();
-static SLJIT_FUNC int func() { ... }
^~~~~~~~~~ syntax error (on MSVC)
+typedef (SLJIT_FUNC *func_t)();
+static int SLJIT_FUNC func() { ... }
```
> Fix SLJIT_FUNC calling convention in tutorial

- sljit_src/sljitExecAllocator.c
Has been tested extensibly (albeit not using real hardware/software but a POSIX look alike) and while is expected to work it might not be as efficient/secure/elegant as it could be, because it needs to return writeable pages for consistency with the other allocators, and also needs to update metadata in those executable pages and therefore has to make the pages writeable more often than ideal.
Since enabling MAP_JIT adds undocumented restrictions to the use of those pages, would be important to confirm that notarized applications with the right entitlement (com.apple.security.cs.allow-jit) to allow creating JIT pages, can still use those pages after fork() and if it doesn't raise the issue with Apple ASAP.
if fork() is no longer restricted it might be worth enabling MAP_JIT …
> Apple Bigsur support

- sljit_src/sljitUtils.c
likely to be useful in really old systems that predate POSIX and that
have at least SUSv2 support (not HP-UX)
avoid breaking in at least FreeBSD 13 when building with _POSIX_SOURCE
> util: allow get_page_alignment to work in pre POSIX systems

- sljit_src/sljitExecAllocator.c
- sljit_src/sljitWXExecAllocator.c
starting with FreeBSD 13 an additional restriction on the way page
permissions are allowed to shift was added by indicating at mmap
time the maximum expected value using PROT_MAX.
indicate that the allocated page is also expected to have execute
permissions to avoid future silent failures at mprotect time.
> freebsd: add support for PROT_MAX (since 13)

- sljit_src/sljitUtils.c
Fix two problems in one go:
- The read of `allocator_lock` is not atomic, and races against the write
a few lines below. The Interlocked API docs clearly state [1]:
> "This function is atomic with respect to calls to other interlocked
> functions."
A plain read is *not* atomic (see below).
- There is no read barrier to acquire the memory pointed by `allocator_lock`;
therefore, the write barrier inserted by the Interlocked API a few lines
below does not synchronize with a non-NULL read. (A non-NULL read may
not find the memory pointed by `allocator_lock` committed yet.)
There are two possible solutions, a MSVC-specific one and a generic one.
MSVC-specific would be to mark `allocator_lock` as volatile. volatile
has almost nothing to do with atomicity and synchronization, except on
MSVC on …
> Fix initialization of the allocator_lock on Win32

- API_CHANGES
- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeS390X.c
- test_src/sljitTest.c
I tested the patch with PCRE2, it worked.
> Rework the status flag management of s390x.

- sljit_src/sljitExecAllocator.c
as reported in BUG2769[1], it could result in a miscompiled binary
if using a Big Sur SDK but targeting and older version without the
call.
since macOS in Apple Silicon has a hard requirement for this API in
JIT pages, abort with an error for versions older than Big Sur.
while at it, add quotes around another #error call for consistency.
[1] https://bugs.exim.org/show_bug.cgi?id=2769
> apple: restrict calling pthread_jit_write_protect_np to macOS >= 11

- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativeS390X.c
Since d345a64 (misc: build/documentation fixes from recent changes
(#113), 2022-02-13), and as initially fixed in 92fcb0f (Fix fallthrough
errors., 2022-02-13); the build will be broken in modern versions of gcc
that will warn with -Wimplicit-fallthrough (included as part of -Wextra).
Make sure all architectures have the corresponding tags to avoid this
as required.
Additionally, avoid -Wunused-parameter errors from s390x from parameters
that weren't needed or are still pending implementation.
> misc: fix -Wextra related errors

- sljit_src/sljitConfigInternal.h
both issues introduced with 0863c54 (Support Android ARM64
cacheflush. Patch by Tavian Barnes., 2016-04-06) and might affect also PPC.
per gcc's bug(link in code), the builtin in clang (eventhough it might be only 64-bit) might be ok to use but don't have a way to test that and the fallback works fine otherwise.
> sparc: avoid NOP implementation for clear_cache with gcc

- sljit_src/sljitConfigInternal.h
Since 0863c54 (Support Android ARM64 cacheflush. Patch by Tavian Barnes.,
2016-04-06), the fallback to avoid using gcc's builtin has been masked if
the compiler also supported __has_builtin.
Shown breaking tests 11 and 12 in Debian 12 ppc64le
> power: avoid bogus clear_cache builtin in gcc >= 10

- sljit_src/sljitConfigInternal.h
Practically not needed, as the current code will otherwise fallthrough
to the gcc check below that sets the builtin (which does nothing) for
gcc < 10 (like Ubuntu 20.04 or RHEL 8) or never hit this for gcc >= 10.
> s390x: be explicit about cache coherence needs

- sljit_src/sljitConfigInternal.h
Since 75a5556 (power: avoid bogus clear_cache builtin in gcc >= 10 (#118),
2022-03-18), builds in macOS/arm64 will fail because of a missing function
definition for sys_icache_invalidate.
The reason why that code is suddenly excercised, is because before the
excemption added in that commit, clang will report its builtin and use
that instead.
Using the builtin in arm is problematic, because it could fail and the
builtin doesn't report failures[1] and so it is better to use the system
specific code in this case, but to do so the header needs to be added and
the parameters cast to the correct types.
As a sideeffect, the use of an APPLE specific API unbreaks the build in
iOS, so add a comment to take that into consideration when/if using the
builtin with clang is preferred later.
To avoid …
> macos: fix recent regression breaking build in macos/arm64e

- sljit_src/sljitNativeMIPS_common.c
breaking (because of -Werror) in OpenBSD/mips64 7.0 with messages like :
sljit_src/sljitNativeMIPS_common.c:1767:63: warning: implicit conversion changes signedness: 'int' to 'sljit_u32' (aka 'unsigned int') [-Wsign-conversion]
sljit_u32 flags = (GET_OPCODE(op) == SLJIT_CONV_F64_FROM_SW) << 21;
> mips: avoid sign conversion warnings with clang

- sljit_src/sljitLir.c
Fix building with MinGW in Windows using either gcc or clang x86_64 target compilers.
Tested not to introduce regressions to MSVC builds with either Visual Studio or clang (CLangCL toolset) compilers.
> windows: allow building with MinGW64 gcc/clang

- sljit_src/sljitWXExecAllocator.c
Fixing support for the EOL (mid 2020) 7.2 version (or even older) could be added with minimal changes (as shown in the first [iteration](/carenas/sljit/tree/oldnetbsd-support), but long term it is better to drop support and clean the codebase (as shown in the current patchset) even if the change is more intrusive.
> wxexec: drop suport for NetBSD < 8

- API_CHANGES
- sljit_src/sljitConfigInternal.h
- sljit_src/sljitNativePPC_common.c
- test_src/sljitTest.c
substract(ion) -> subtract(ion)
> Fix spelling of 'subtract'

- sljit_src/sljitNativeARM_64.c
Likely some missing code during recent refactorings and most likely to affect macOS in Apple Silicon
> build failure at least with clang in 64bit arm

- sljit_src/sljitNativeRISCV_common.c
breaking test15 consistently when building against both available riscv nodes in the GCC compiler farm[1]
[1] https://cfarm.tetaneutral.net/machines/list/#
> riscv: avoid SIGILL in 64bit while jumping

- sljit_src/sljitConfig.h
- sljit_src/sljitConfigInternal.h
Since it is only required as part of "protexec", it shouldn't need to be provided also by external allocators.
Expand the fallback definition, so that the only two macros that are required are the ones that point to the external functions to allocate and free executable memory.
Keep using one if it is already provided for backward compatibility.
> config: remove SLJIT_EXEC_OFFSET from list of required macros for an external allocator

- sljit_src/sljitConfigInternal.h
Avoid misdetection of armv8 (or newer) systems by using a more standard and forward compatible macro of __ARM_ARCH.
Not sure exactly which release it was introduced with, but the gcc commit that did is from May 2012 and clang seems even older.
tested with gcc 5.5 (from NetBSD 8.2) and gcc 4.8.2 and clang 3.6 (from Ubuntu 14.04)
> config: improve autodetection for ARM

- sljit_src/sljitNativeRISCV_common.c
Mainly deal with the fact that the FPU was always enabled, even though is optional, and therefore it would fail if running the tests in a soft-float system.
Most OS target lp64d at a minimum though and most commercially available CPUs seem to include an FPU and the extensions to use it on its ISA, so no "distribution" is affected.
> riscv: allow disabling the FPU on demand or if soft-float ABI is requested

- sljit_src/sljitNativeX86_common.c
There are no checks in conv_f64_from_sw or conv_sw_from_f64 on x86_32 for virtual registers, so the conversion will be incorrect if the word register happens to be virtual. This fixes that.
Simple test case:
```
#include "sljit_src/sljitLir.h"
#include <stdio.h>
int main()
{
struct sljit_compiler *compiler;
sljit_sw (*f1)(sljit_f64);
sljit_f64 (*f2)(sljit_sw);
compiler = sljit_create_compiler(NULL, NULL);
sljit_emit_enter(compiler, 0, SLJIT_ARGS1(W, F64), 4, 0, 1, 0, 0);
sljit_emit_fop1(compiler, SLJIT_CONV_SW_FROM_F64, SLJIT_R3, 0, SLJIT_FR0, 0);
sljit_emit_return(compiler, SLJIT_MOV, SLJIT_R3, 0);
f1 = sljit_generate_code(compiler);
sljit_free_compiler(compiler);
printf("%d\n", (int) f1(1234));
compiler = sljit_create_compiler(NULL, NULL);
sljit_emit_enter(compiler, 0, SLJIT_ARGS1(F64, …
```
> Virtual register checks in floating point conversions

- sljit_src/sljitConfigInternal.h
Reformat previously added line for readability, add armv9 and most importantly make sure all parenthesis are paired and there are no typos.
> config: really improve autodetection for arm

- sljit_src/allocator_src/sljitExecAllocatorApple.c
Make the Apple Silicon code smarter, so it can allow binaries built for not existent OS versions, to easy the pain of "fat binary" builders that need to target older versions than Big Sur.
Since those OS versions are not available, it can be safe to assume that the code can't fail at runtime either, but it will need adjusting if support is added for non macOS or other toolchains than clang (with compiler_rt) as provided by Xcode.
Note that since the code generated will have a runtime dependency in the toolchain used to build it, it is inherently non portable and should be ideally linked statically with binaries using the same toolchain.  A warning to make that more obvious to users of this "feature" might be worth adding, but has been punted for this version as it was known to cause …
> macos: allow building with an os target older than 11.0

- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeX86_common.c
- test_src/sljitTest.c
This adds the required opcode defines, checks, tests and implementation for:
- x86_64
- x86_32
- aarch64
- ARM32 (v8 THUMB2)
- ARMv7
> Add atomic instructions

- sljit_src/sljitNativeARM_64.c
As shown when building in Linux/macOS with `-fsanitize=undefined`:
```
$ bin/sljit_test 
Pass -v to enable verbose, -s to disable this hint.
sljit_src/sljitNativeARM_64.c:1964:13: runtime error: left shift of negative value -9223372036854775808
sljit_src/sljitNativeARM_64.c:1936:13: runtime error: left shift of negative value -2147483648
```
> arm64: avoid undefined behaviour with signed shifts

- sljit_src/sljitLir.h
- sljit_src/sljitNativeX86_common.c
- test_src/sljitTest.c
test 92 case 1 not failing because of an unlucky choice of test values.
> x86_64: correctly detect mode32 for atomic_store

- sljit_src/sljitNativeARM_64.c
- test_src/sljitTest.c
Works only on CPUs that implement LSE, and which is available since armv8.1-a (--march=armv8-a+lse), like the M1.
First patch implement the feature, last one is just leftover code that might be useful while debugging and therefore optional
> arm64: alternative implementation of atomics using CAS

- sljit_src/sljitLir.h
- sljit_src/sljitNativeARM_64.c
- test_src/sljitTest.c
Use MOV when appropriate, make test92 case 50 big endian safe and cleaner and documentation update
> tidy up #164

- sljit_src/sljitNativeS390X.c
A solution for the problem documented in #173 and that provided a partial fix for half sized atomics
> s390x: fix atomic store emulation when offset in higher int

- sljit_src/sljitNativeARM_64.c
This now uses the same offset calculation as sljit_generate_code. Before, if you had an address that was 16 bytes off from the maximum, it would overflow the 26 bit signed int available to the "bl" instruction. In other words, it would choose "bl" when it should have chosen "blr". This typically caused a crash because the jump was to an invalid address.
> Fix incorrect branch offset calculation

- sljit_src/sljitLir.c
Usually triggered by gcc for non ARM/x86 architectures
> simd: avoid unused parameter warnings

- sljit_src/sljitConfigInternal.h
via macports, allows pcre2 to build with jit support on OS X 10.4
> Be explicit about OS version

- regex_src/regexMain.c
- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_T2_32.c
- test_src/sljitTest.c
NEON was introduced as an optional feature with armv7, so disable it for earlier versions.
> simd: prevent SIGILL with armv6

- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_T2_32.c
Tested with `qemu-system-arm -cpu cortex-a15` and AMD Opteron 1100
Fixes: #185
> arm: use armv6 compatible instructions for thumb2 in atomic

- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_T2_32.c
vmov.f32(NEON) and vmov.f64(VFPv3) will trigger SIGILL otherwise in test93 when running in an older CPU (ex: arm1136 in Raspberry PI < 2)
> arm: restrict NEON code in sljit_emit_fset{32,64}

- sljit_src/sljitNativeARM_T2_32.c
Mask up to 12bits for the offset to avoid truncation. Triggering in test79 case 21 when running in QEMU, somehow
> arm: fix not aligned register pair thumb2 operations

- sljit_src/sljitLir.c
mainly to avoid unused function warnings with clang on the architectures that are yet to be implemented
> atomic: avoid unused checks if not implemented

- sljit_src/sljitNativeMIPS_32.c
This fixes errors in test93 that are interestingly enough only showing for big endian.
> mips: fix implementation of sljit_emit_fset64 in 32bit mips (BE)

- sljit_src/sljitNativeS390X.c
Mostly to avoid UB with shifts of negative numbers.
> s390x: sanitize warnings with clang 15

- sljit_src/sljitConfigInternal.h
- sljit_src/sljitNativeMIPS_32.c
- sljit_src/sljitNativeMIPS_64.c
- sljit_src/sljitNativeMIPS_common.c
- test_src/sljitTest.c
Mostly fixes issues when running through `qemu` and compatibility with newer CPUs that don't support or discourage the use of emulated 32bit FPU registers.
It doesn't address all endianess issues though but will run cleanly in both 32/64bit big endian and addresses manipulation of unaligned doubles which need to be loaded in the right order to avoid unpredictable values as described in:
```
When paired with MTC1 to write a value to a 64-bit FPR, the MTC1 must be executed first, followed by the MTHC1.
This is because of the semantic definition of MTC1, which is not aware that software is using an MTHC1 instruction
to complete the operation, and sets the upper half of the 64-bit FPR to an UNPREDICTABLE value. 
```
> mips: correctly detect valid FPU and support StatusFR=1 in 32bit

- sljit_src/sljitNativeMIPS_32.c
- sljit_src/sljitNativeMIPS_common.c
Addresses the remaining issues shown in little endian systems:
```
carenasgm@gcc23:~/src/sljit$ bin/sljit_test
Pass -v to enable verbose, -s to disable this hint.
test58 case 1 failed
test59 case 5 failed
test77 case 7 failed
test79 case 21 failed
SLJIT tests: 4 (3%) tests FAILED on MIPS III 32bit (little endian + aligned) (with fpu)
```
> mips: fix endianess issues

- doc/overview.txt
- sljit_src/sljitNativeMIPS_common.c
- test_src/sljitTest.c
Adds 3 instructions from "revision 2" that allow for a new implementation of `SLJIT_REV` (and friends) that should be good enough to enable the corresponding `sljit_has_cpu_feature()` flag.
[documentation](https://github.com/zherczeg/sljit/blob/3dcdb25754363db2cd34dbd1cd9a6a6b880cadae/doc/overview.txt#L41-L44) for what is an invalid operation has been also updated.
> mips: enable SLJIT_HAVE_REV for SLJIT_MIPS_REV >= 2

- sljit_src/sljitNativePPC_32.c
- sljit_src/sljitNativePPC_common.c
- test_src/sljitTest.c
```
[carenasgm@gcc120 sljit.base]$ bin/sljit_test 
Pass -v to enable verbose, -s to disable this hint.
test87 case 3 failed
SLJIT tests: 1 (0%) tests FAILED on PowerPC 64bit (little endian + unaligned) (with fpu)
```
where:
```
test87 case 3 expected 0x0807060504030201 got 0x0403020108070605
test87 case 5 expected 0x8877665544332211 got 0x4433221188776655
```
> ppc: fix SLJIT_REV for 64bit little endian

- GNUmakefile
- sljit_src/allocator_src/sljitExecAllocatorApple.c
- sljit_src/sljitLir.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeRISCV_common.c
- sljit_src/sljitNativeS390X.c
Mostly simple "fixes" to avoid warnings, but also some improvements to the Makefile to help with future related work.
The new makefile options have defaults that keep the old behaviour.
> build: fix warnings with gcc12 and related improvements

- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeLOONGARCH_64.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeRISCV_common.c
- sljit_src/sljitNativeS390X.c
- sljit_src/sljitNativeX86_common.c
Improves support of older FPUs in 64bit while hopefully cleaning up the code slightly.
As a bonus would allow detecting the FPU in: `qemu-mips64-static -cpu 5Kf`
> mips: improve FPU detection also for MIPS64

- sljit_src/sljitLir.c
- sljit_src/sljitNativeARM_64.c
- test_src/sljitTest.c
Mostly to avoid some warning when building for aarch64 with `-march=armv8.1-a` or higher, but also adds test cases for bugs found in LoongArch and s390x implementations among other improvements.
> arm: small improvements for atomics with LSE

- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeS390X.c
Include the additional data added in some architectures at the end of the generated code to the reported `executable_size`
Fixes: #207
> s390x: make sljit_generated_code_size() accurate

- sljit_src/sljitNativeX86_common.c
Splunk discovered a bug in PCRE2 which derives from the SLJIT code on x86_64. 
In particular the JIT would generate a 5-byte 32-bit relative call instruction with a jump of -0x80000003. This is just over what fits in 32-bits. Thus on the second pass when the address was inserted, it would get truncated to 0x7ffffffd which is now a positive jump address. This is a difference of exactly 0x100000000 - because the highest bit got dropped. The JIT should have realized that 0x80000003 would not fit in a 32-bit jump/call, and used a 64-bit instruction instead.
This is PIC code, so jumps are relative. On x86 call relative is relative to the next instruction.
In x86_64 (ia32e) the call relative instruction can have a 32-bit or a 64-bit operand. Both versions are allowed (the 16-bit version is …
> Fix for generation of jump relative x86 instruction, arithmetic bug in decision between 32 and 64 bit address.

- sljit_src/sljitConfigInternal.h
Implements a portability suggestion from #179
It is important to note that albeit undocumented, Apple compilers set the original macro as well, so this will only prevent the unnecessary fallback that was required for other compilers in that architecture.
> config: use standard interface to detct macOS version

- doc/tutorial/sljit_tutorial.html
- sljit_src/allocator_src/sljitExecAllocatorApple.c
- test_src/sljitTest.c
needed at least for macOS versions older than 10.6 and corrects a regression from a previous refactoring that changed the intention of the code as documented to use MAP_JIT in non macOS if defined.
> allocator: add support for PowerPC in Apple

- sljit_src/sljitNativeX86_common.c
Fixes a FTBFS when building a PCRE2 library that includes this change in 32bit Linux.
The problem might be only triggered by older compilers (using gcc 4.9.2-10+deb8u2) as using clang version 3.5.0-10 in the same system succeeds even without the patch
> x86: avoid clobbering "ebx register" during CPU detection (32-bit)

- GNUmakefile
- sljit_src/sljitLir.c
While at it, add the relevant warning to the default list so this kind of issues are easier to detect.
> s390x: fix FTBFS with clang

- GNUmakefile
- doc/tutorial/array_access.c
- doc/tutorial/brainfuck.c
- doc/tutorial/struct_access.c
- sljit_src/sljitLir.c
- sljit_src/sljitNativeX86_common.c
While `-pedantic` is all that is needed together with an `-std` version; adding `-Wpedantic` allows for some "extra" and has been supported by `clang` for  a long while as well as by `gcc >= 4.8`.
The non C89 compliant parts of `s390x` could be addressed later, but are unlikely to be ever needed under the currently supported environments; the same goes for `ppc` where using a `void *` for a function is not valid C (because pointers to data and code can have different sizes), but is required for POSIX, and all systems using that CPU usually conform to that.
> build: make code mostly ANSI C89 compatible

- sljit_src/sljitNativeRISCV_common.c
This was discovered while running pcre2 tests on QEMU with Sv48 kernel. This 
patch fixes `getput_arg()` and `load_addr_to_reg()` for large immediate cases.
Tested with sljit tests and pcre2 tests.
Reported-by: Felix Yan <felixonmars@archlinux.org>
Reported-by: dramforever <dramforever@live.com>
> riscv: fix getput_arg and load_addr_to_reg

- regex_src/regexJIT.c
- sljit_src/sljitConfigInternal.h
While at it, make sure the default "allocator" macros are safe to use in all configurations.
> regex: allow building with a C++ compiler

- sljit_src/sljitLir.c
- sljit_src/sljitNativeLOONGARCH_64.c
Sync recent changes on LoongArch64, including `reduce_code_size` function, tested under QEMU virt machine.
Solved https://github.com/zherczeg/sljit/issues/232
> Support recent changes on LoongArch64

- sljit_src/allocator_src/sljitExecAllocatorApple.c
The headers on some older macOS versions don't define MAP_JIT at all.
> Fix build on older macOS

- sljit_src/sljitNativeLOONGARCH_64.c
Fix failed floating point select tests for LoongArch 64, tested under AOSC Linux running on Loongson 3A6000.
> Fix LoongArch floating point select tests

- sljit_src/allocator_src/sljitExecAllocatorCore.c
The locked section needs to extend until we are done modifying internal block offsets and sizes, otherwise we risk running into data corruption in a multi-threaded context.
This bug was introduced in 7de0fee9a7376b33e31a3903487cd9933da3a606
See: https://github.com/PCRE2Project/pcre2/issues/402
> Fix locking region in sjlit_malloc_exec

- sljit_src/sljitLir.c
- sljit_src/sljitLir.h
- sljit_src/sljitNativeLOONGARCH_64.c
Implement LoongArch 128-bit LSX & 256-bit LASX SIMD for sljit, tested on both 3C5000/3A6000 CPUs.
It's worth noting that the LoongArch doesn't guarantee when using LSX instruction on LASX register, the upper 128-bit will stay the same. LA464 & LA664 have slightly difference on LASX instrunction's operation. You can find these difference and LoongArch SIMD instruction guide on this website [Unofficial LoongArch Intrinsics Guide](https://jia.je/unofficial-loongarch-intrinsics-guide/).
> Implement LoongArch LSX and LASX SIMD Support

- sljit_src/sljitNativeLOONGARCH_64.c
According to what @carenas pointed, the LoongArch SIMD code will fail to complete test_simd9 case10, it's related to that in case10, we use `SLJIT_TMP_DEST_REG`, this reg is equal to reg `$ra` or `TMP_REG2` in LoongArch, and it's confilct to `sljit_emit_simd_lane_mov`, so replace it with `TMP_REG3`. 
This is due to I forget to update my codebase while developing LoongArch SIMD code, and the test_simd9 case10 wasn't there at the time. Again, big thanks to @carenas, and sorry for my carelessness.
> Fix TMP_REG2 usage fault in sljit_emit_simd_lane_mov for LoongArch

- sljit_src/sljitNativeX86_common.c
Protect against oldest CPUs that might leave bogus values after `cpuid` affecting the feature detection.
The "bug" for leaf 1 could affect several old CPUs as it matches the original specification for `cpuid`, possibly including:
> AMD (Am486 DX2/DX4, Am5x86, K5)
> Centaur (WinChip C6, Winchip 2)
> NexGen (Nx586)
> Cyrix (Cx486DX2/DX4, 5x86, 6x86, 6x86MX, MII)
> x86: check for extended function availability before using

- sljit_src/sljitNativeX86_common.c
Fix a SIGILL crash in machines with Intel's Sandy Bridge, Ivy Bridge as well as the three first generation of AMD Bulldozer and other equivalent CPUs
> x86: avoid SIGILL in CPUs with AVX but without AVX2

- sljit_src/sljitNativeLOONGARCH_64.c
- sljit_src/sljitNativeMIPS_common.c
Implement ll/sc for loongarch atomic load & store, also fix amcas bugs.
Tested under 3C5000 and 3A6000 (with amcas support).
> loongarch: Implement ll/sc support for atomic operations

- sljit_src/sljitNativeRISCV_common.c
Avoid SIGILL when the CPU/OS/toolchain doesn't support the vector extension and that is fairly common in currently available systems.
> riscv: only enable SIMD if supported by system

- .github/workflows/actions.yml
Add action for testing sljit on different architectures
> Add action

- sljit_src/sljitNativeLOONGARCH_64.c
Implement LoongArch `dbar 0` memory fence, which is a full memory barrier just like `fence iorw, iorw` on RISC-V.
Also support tmp register for atomic, it worth noticing that `TMP_REG2` seems to have collision issues, so I use `TMP_REG3` instead.
Done: https://github.com/zherczeg/sljit/issues/262
> loongarch: add memory fence & support tmp register for atomic

- sljit_src/sljitConfigInternal.h
Remove dependency on internal macro SSIZE_OF.
> Enable public usage of SLJIT_LOCALS_OFFSET

- sljit_src/sljitNativeARM_64.c
Implement SLJIT_BREAKPOINT with the same instruction emitted by MSVC for the __debugbreak intrinsic (brk #0xf000) and by Clang for __builtin_debugtrap. On Windows, this triggers a breakpoint exception just as int3 does on x86. The previously emitted instruction (brk #0) triggers an illegal instruction exception instead.
LLDB also has special handling for this brk variant on Windows and macOS, automatically advancing to the next instruction so execution can be easily continued.
Fixes #266
> Emit brk #0xf000 for breakpoint opcode on arm64

- GNUmakefile
- doc/tutorial/array_access.c
- doc/tutorial/brainfuck.c
- doc/tutorial/branch.c
- doc/tutorial/first_program.c
- doc/tutorial/func_call.c
- doc/tutorial/loop.c
- doc/tutorial/sljit_tutorial.html
- doc/tutorial/struct_access.c
- doc/tutorial/temp_var.c
Get examples building again on all platforms and make them functional for the first time on Win64.
Fixes #246
> Fix examples

- .github/workflows/actions.yml
Update the run-on-arch-action to resolve the arm/aarch64/s390x CI failure.
> CI: Update uraimo/run-on-arch-action to 2.8.1

- GNUmakefile
- sljit_src/allocator_src/sljitExecAllocatorCore.c
- sljit_src/sljitNativeS390X.c
PCRE2 uses `-Wshadow`, so it's helpful if the sljit code does as well.
Some errors seem to have crept in to the Mac-only (or rather, ARM-only) code which wasn't noticed until I tried a PCRE2 build on that platform, in one of the build configurations using `-Wshadow`.
> Enable -Wshadow warning

- sljit_src/sljitLir.c
- sljit_src/sljitNativeLOONGARCH_64.c
Fix failed testcases and enbale sljit_emit_op2cmpz for loongarch, tested under 3A6000.
> loongarch: Fix sljit_emit_single and sljit_emit_op2cmpz

- sljit_src/sljitNativeX86_64.c
- test_src/sljitTestCall.h
In current version SLJIT, sljit_emit_icall only save "RDI" if word_arg_count >= 3. But RDI is the first argument according to Linux x86_64 calling convention,
in other words, below code will cause SegFault on current version SLJIT.
```c
sljit_emit_op1(compiler, SLJIT_MOV, SLJIT_R0, 0, SLJIT_IMM, 10);
sljit_emit_op1(compiler, SLJIT_MOV, SLJIT_R1, 0, SLJIT_IMM, 16);
sljit_emit_op1(compiler, SLJIT_MOV, SLJIT_R2, 0, SLJIT_IMM, SLJIT_FUNC_ADDR(func2));
sljit_emit_icall(compiler, SLJIT_CALL, SLJIT_ARGS2(W, W, W), SLJIT_R2, 0);
```
BTW sljit  failed on windows in test_float13, with large stack test. 
Is it known issue? Should we decrease the SLJIT_MAX_LOCAL_SIZE on windows?
> Fix sljit_emit_icall on Linux x86_64

- .github/workflows/actions.yml
- sljit_src/sljitNativeLOONGARCH_64.c
Update toolchain to the lastest 2025.02.21 version & some minor code style change to maintain the consistency of codebase.
> loongarch: Update toolchain and minor code style change

- sljit_src/sljitNativeLOONGARCH_64.c
Stop emitting `ori` while the immediate's lower 12-bit is zero in immediate generator.
> loongarch: improve immediate generator

- docs/website/docusaurus.config.js
Tried to test the deployment to a `gh-pages` branch and noticed this small mistake in the configuration.
> Fix Docusaurus URL configuration

- sljit_src/sljitConfigInternal.h
- sljit_src/sljitLir.c
- sljit_src/sljitNativeARM_32.c
- sljit_src/sljitNativeARM_64.c
- sljit_src/sljitNativeARM_T2_32.c
- sljit_src/sljitNativeLOONGARCH_64.c
- sljit_src/sljitNativeMIPS_common.c
- sljit_src/sljitNativePPC_common.c
- sljit_src/sljitNativeRISCV_common.c
- sljit_src/sljitNativeS390X.c
- sljit_src/sljitNativeX86_common.c
Move from using comments (supported by gcc since version 7 both as C and C++) to use attributes (with preference for the official one that gcc-15 defaults to, as it is included in C23 and that came from C++17).
> config: add SLJIT_FALLTHROUGH to annotate case fallthroughs

- sljit_src/sljitNativeLOONGARCH_64.c
- test_src/sljitTest.c
Implement `sljit_emit_op2_shift`, loongarch do not have a bit-manipulation extension like RISC-V does, so use plain `shift + add` instead, tested on Loongson 3A6000, also fix a typo in `sljitTest.c`.
> loongarch: Implement sljit_emit_op2_shift

- sljit_src/allocator_src/sljitWXExecAllocatorPosix.c
Allow running in NetBSD with the WX executable allocator.
> netbsd: allow mprotect exception for PAX in wxalloc
